apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spotinst-metrics-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spotinst-metrics-exporter.labels" . | nindent 4 }}
data:
  SPOTINST_ACCOUNT: {{ required ".Values.spotinst.account is required" .Values.spotinst.account | b64enc }}
  SPOTINST_TOKEN: {{ required ".Values.spotinst.token is required" .Values.spotinst.token | b64enc }}
