apiVersion: v1
kind: Service
metadata:
  name: {{ include "spotinst-metrics-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spotinst-metrics-exporter.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "spotinst-metrics-exporter.selectorLabels" . | nindent 4 }}
